#!/bin/sh
# kFreeBSD do not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          skeleton
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.  This example start a
#                    single forking daemon capable of writing a pid
#                    file.  To get other behavoirs, implemend
#                    do_start(), do_stop() or other functions to
#                    override the defaults in /lib/init/init-d-script.
### END INIT INFO

HYDRA_HOME="/home/pi/hydra"
USER="pi"

# if the executables do not exist -- display error

if [ ! -f $HYDRA_HOME/start.sh -o ! -d $HYDRA_HOME ]
then
        echo "Hydra startup: cannot start"
        exit 1
fi

# depending on parameter -- startup, shutdown, restart 

case "$1" in
    start)
        # Hydra listener and instance startup
        echo -n "Starting Hydra: "
        su - $USER -c $HYDRA_HOME/start.sh
        touch /var/lock/hydra
        echo "OK"
        ;;
    stop)
 	# Hydra shutdown
        echo -n "Shutdown Hydra: "
        su - $USER -c "$HYDRA_HOME/stop.sh"
        rm -f /var/lock/hydra
        echo "OK"
        ;;
    reload|restart)
        $0 stop
        $0 start
        ;;
    *)
        echo "Usage: $0 start|stop|restart|reload"
        exit 1
esac
exit 0
